name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Create config file
        run: |
          echo "export const config = {
            emailjs: {
              serviceId: '${{ secrets.VITE_EMAILJS_SERVICE_ID }}',
              templateId: '${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}',
              publicKey: '${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}'
            }
          };" > src/config.ts

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
