name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Create config file
        run: |
          echo "export const config = {
            emailjs: {
              serviceId: '${{ secrets.VITE_EMAILJS_SERVICE_ID }}',
              templateId: '${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}',
              publicKey: '${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}'
            }
          };" > src/config.ts

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
